choreapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from chores import views
from django.contrib.auth.decorators import login_required

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', login_required(views.ChoreList.as_view()), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': "/"}),
    # url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^users/(?P<user>\w+)/$', views.user_registered),
    url(r'chore/(?P<pk>\d+)/$', views.UpdateChore.as_view(), name='update_chore'),
    url(r'complete/(?P<chore>\d+)/$', views.complete, name='complete'),
    url(r'leaderboard/$', views.UserList.as_view(), name='leaderboard')
    # url(r'rankings/', views.rankings, name='rankings')
)

chores/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.conf import settings


class Chore(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    date_completed = models.DateField(blank=True, null=True)
    date_added = models.DateField(auto_now_add=True)
    points = models.IntegerField(default=0)
    completed = models.BooleanField(blank=True, default=False)
    completed_by = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return "{0}".format(self.title)

    def get_absolute_url(self):
        return reverse('home')


class Score(models.Model):
    user = models.OneToOneField(User, unique=True)
    points = models.IntegerField(default=0)

    def __str__(self):
        return "{0}".format(self.points)

def create_user_score(sender, instance, **kwargs):
    user_score = Score.objects.get_or_create(user=instance)
    # user_score.save()


models.signals.post_save.connect(create_user_score , sender=User)

chores/views.py
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.views.generic import ListView, UpdateView
from .models import Chore
from datetime import date
# from .tasks import reset_chore
from django.shortcuts import redirect
from django.contrib.auth import get_user_model


class ChoreList(ListView):
    template_name = "chores/chore_list.html"
    model = Chore
    context_object_name = "chores"

    def get_queryset(self):
        return Chore.objects.filter(completed=False)

    def post(self, request, *args, **kwargs):
#         print(request['POST'])
        return Chore.objects.filter(completed=False)


class UpdateChore(UpdateView):
    model = Chore
    initial = {'completed': True, 'date_completed': date.today()}
    # fields = ["completed_by"]
    context_object_name = "chore"


class UserList(ListView):
    template_name = "users/index.html"
    model = User
    context_object_name = "users"


def user_registered(request, user):
    message = "{0} has been registered.".format(user)
    return HttpResponse(message)


def complete(request, chore):
    user_name = request.POST['completed_by']
    completed_chore = Chore.objects.get(pk=chore)
    completed_chore.completed = True
    completed_chore.completed_by = user_name
    user_model = get_user_model()
    current_user = user_model.objects.get(username=user_name)
    current_user.score.points += completed_chore.points
    current_user.score.save()
    completed_chore.save()
    return redirect('home')

chores/templates/chores/chore_form.html
{% extends "foundation/base.html" %}
{% block base_body %}
<div class='row'>
    <div class='large-12 columns'>
        <div class='panel'>
            <form action="." method='POST'>{% csrf_token %}
               <h1>{{chore.title}}</h1>
               {{form.as_p}}
               <input type='hidden' id='id_completed_by' name='completed_by' value="{{ user.username }}">
               <input type='hidden' id="id_completed" name="completed" value="True">
               <input type='submit' value='Done!'>
            </form>
        </div>
    </div>
</div> 
{% endblock base_body %}

chores/templates/chores/chore_list.html
{% extends 'chores/index.html' %}
{% block content %}
    <div class="row" id='title'>
        <div class="large-12 columns">
            <h1>Chores to be Done!</h1>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <div class="panel">
                {% for chore in chores %}
                    <p><h3>Title: {{chore.title}}</h3>
                    <p><span class="worth">This chore is worth {{chore.points}} points.</span>
                    <form action="/complete/{{chore.pk}}/" method='POST'>{% csrf_token %}
                        <input type='hidden' id='id_completed_by' name='completed_by' value="{{ user.username }}">
                        {# <input type='hidden' id="id_completed" name="completed" value="True"> #}
                        <input type = 'submit' value = 'I did it!'>
                    </form>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

chores/templates/chores/index.html
{% extends "foundation/base.html" %}
{% block base_body %}
{% block nav %}
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class="name">
            <h1><a href="{% url 'home' %}">Home</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
            <li class="active"><a href={% url "leaderboard" %}>Who's Winning?</a></li>
            <li class="secondary"><a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
            {% if user.is_superuser %}
    		      <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% endif %}
          <!--
    		<li class="has-dropdown">
            	<a href="#">Right Button Dropdown</a>
            	<ul class="dropdown">
              	<li><a href="#">First link in dropdown</a></li>
              	<li class="active"><a href="#">Active link in dropdown</a></li>
            </ul>
     -->
        </ul>

    <!-- Left Nav Section -->
    <!--
<ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
 -->
    </section>
</nav>
{% endblock nav %}
{% block content %}{% endblock content %}

{% endblock base_body %}

chores/templates/foundation/base.html
{% load static %}
{% load foundation_tags %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block meta %}{% endblock meta %}
    {% block base_title %}
    <title>{% block title %}{% endblock title %}</title>
    {% endblock base_title %}

    {# Base Foundation CSS #}
    {% block foundation_css %}
    {% foundation_css "normalize" %}
    {% foundation_css "foundation.min" %}
    {% endblock foundation_css %}  
    
    {# Custom CSS #}
    {% block css %}<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">{% endblock css %}

    {# Override if you need another version of modernizr #}
    {% block foundation_modernizer %}
    {% foundation_vendor "modernizr" %}
    {% endblock foundation_modernizer %}

    {# Custom head JS #}
    {% block head_js %}{% endblock head_js %}
</head>
<body {% block body_attr %}{% endblock body_attr %}>
    {# Main content goes here #}
    {% block base_body %}{% endblock base_body %}

    {# Override if you need another version of jQuery #}
    {% block foundation_jquery %}
    {% foundation_vendor "jquery" %}
    {% endblock foundation_jquery %}

    {# Foundation JS #}
    {% block foundation_js %}
    {% foundation_js %}
    {% endblock foundation_js %}

    {# Custom JS #}
    {% block body_js %}{% endblock body_js %}

    {# Init Foundation #}
    {% block foundation_js_init %}
    <script>
        $(document).foundation();
    </script>
    {% endblock foundation_js_init %}
</body>
</html>

chores/templates/foundation/index.html
{% extends "foundation/base.html" %}

{% block base_body %}

    <div class="row">
      <div class="large-12 columns">
        <h1>Welcome to Foundation</h1>
      </div>
    </div>
    
    <div class="row">
      <div class="large-12 columns">
      	<div class="panel">
            {% for chore in chores %}
                {{chore.title}}
                {{chore.points}}
            {% endfor %}
	        <div class="row">
	        	<div class="large-4 medium-4 columns">
	    		<p><a href="http://foundation.zurb.com/docs">Foundation Documentation</a><br />Everything you need to know about using the framework.</p>
	    	</div>
	        	<div class="large-4 medium-4 columns">
	        		<p><a href="http://github.com/zurb/foundation">Foundation on Github</a><br />Latest code, issue reports, feature requests and more.</p>
	        	</div>
	        	<div class="large-4 medium-4 columns">
	        		<p><a href="http://twitter.com/foundationzurb">@foundationzurb</a><br />Ping us on Twitter if you have questions. If you build something with this we'd love to see it (and send you a totally boss sticker).</p>
	        	</div>        
					</div>
      	</div>
      </div>
    </div>

    <div class="row">
      <div class="large-8 medium-8 columns">
        <h5>Here&rsquo;s your basic grid:</h5>
        <!-- Grid Example -->

        <div class="row">
          <div class="large-12 columns">
            <div class="callout panel">
              <p><strong>This is a twelve column section in a row.</strong> Each of these includes a div.panel element so you can see where the columns are - it's not required at all for the grid.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-6 medium-6 columns">
            <div class="callout panel">
              <p>Six columns</p>
            </div>
          </div>
          <div class="large-6 medium-6 columns">
            <div class="callout panel">
              <p>Six columns</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="large-4 medium-4 small-4 columns">
            <div class="callout panel">
              <p>Four columns</p>
            </div>
          </div>
          <div class="large-4 medium-4 small-4 columns">
            <div class="callout panel">
              <p>Four columns</p>
            </div>
          </div>
          <div class="large-4 medium-4 small-4 columns">
            <div class="callout panel">
              <p>Four columns</p>
            </div>
          </div>
        </div>
        
        <hr />
                
        <h5>We bet you&rsquo;ll need a form somewhere:</h5>
        <form>
				  <div class="row">
				    <div class="large-12 columns">
				      <label>Input Label</label>
				      <input type="text" placeholder="large-12.columns" />
				    </div>
				  </div>
				  <div class="row">
				    <div class="large-4 medium-4 columns">
				      <label>Input Label</label>
				      <input type="text" placeholder="large-4.columns" />
				    </div>
				    <div class="large-4 medium-4 columns">
				      <label>Input Label</label>
				      <input type="text" placeholder="large-4.columns" />
				    </div>
				    <div class="large-4 medium-4 columns">
				      <div class="row collapse">
				        <label>Input Label</label>
				        <div class="small-9 columns">
				          <input type="text" placeholder="small-9.columns" />
				        </div>
				        <div class="small-3 columns">
				          <span class="postfix">.com</span>
				        </div>
				      </div>
				    </div>
				  </div>
				  <div class="row">
				    <div class="large-12 columns">
				      <label>Select Box</label>
				      <select>
				        <option value="husker">Husker</option>
				        <option value="starbuck">Starbuck</option>
				        <option value="hotdog">Hot Dog</option>
				        <option value="apollo">Apollo</option>
				      </select>
				    </div>
				  </div>
				  <div class="row">
				    <div class="large-6 medium-6 columns">
				      <label>Choose Your Favorite</label>
				      <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Radio 1</label>
				      <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Radio 2</label>
				    </div>
				    <div class="large-6 medium-6 columns">
				      <label>Check these out</label>
				      <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
				      <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
				    </div>
				  </div>
				  <div class="row">
				    <div class="large-12 columns">
				      <label>Textarea Label</label>
				      <textarea placeholder="small-12.columns"></textarea>
				    </div>
				  </div>
				</form>
      </div>     

      <div class="large-4 medium-4 columns">
			  <h5>Try one of these buttons:</h5>
			  <p><a href="#" class="small button">Simple Button</a><br/>
        <a href="#" class="small radius button">Radius Button</a><br/>
        <a href="#" class="small round button">Round Button</a><br/>            
        <a href="#" class="medium success button">Success Btn</a><br/>
        <a href="#" class="medium alert button">Alert Btn</a><br/>
        <a href="#" class="medium secondary button">Secondary Btn</a></p>           
				<div class="panel">
        	<h5>So many components, girl!</h5>
        	<p>A whole kitchen sink of goodies comes with Foundation. Checkout the docs to see them all, along with details on making them your own.</p>
        	<a href="http://foundation.zurb.com/docs/" class="small button">Go to Foundation Docs</a>          
        </div>
      </div>
    </div>

{% endblock base_body %}

chores/templates/users/index.html
{% extends "chores/index.html" %}
{% block content %}
    <div id = 'leaderboard' class='row'>
        <div class = "large-12 column">
{#             <h1>Who's winning?</h1> #}
            {% for user in users %}
                <p>{{ user.username }} has {{user.score.points}} points.</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}